<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Visual feedback_demo-frame</name>
   <tag></tag>
   <elementGuidId>4038cea5-c3a2-4e47-a410-5a764ab95a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe.demo-frame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c6e05123-e641-4ce6-acac-969ae413b457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/demos/droppable/default.html</value>
      <webElementGuid>3e1db732-41eb-4cba-adee-6599ad8e3111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-frame</value>
      <webElementGuid>6376ca05-1efc-42a1-a1a2-29fbf65bd119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/iframe[@class=&quot;demo-frame&quot;]</value>
      <webElementGuid>b39a5e02-156d-4bb0-a1c1-6e89b8b5cc1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/iframe</value>
      <webElementGuid>460a45ad-f978-4b43-9f17-52657f3498d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>e6a6cc25-2f46-41ad-89b7-27ab77f077a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/resources/demos/droppable/default.html']</value>
      <webElementGuid>b8bc3b14-0a5e-4c5f-826b-8e90feeea6c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
